# We shall use the same dataset used in previous assignment -digits.Make a 80-20 train/test split.

In [1]:
from sklearn import datasets
import matplotlib.pyplot as plt
digits = datasets.load_digits()
print(digits.data)
print(digits.target)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

# To apply a classifier on this data, we need to flatten the image, to
# turn the data in a (samples, feature) matrix:
n_samples = len(digits.images)
transformedData = digits.images.reshape((n_samples, -1))

#print(len(transformedData))
#print(len(digits.target))

train_x, test_x, train_y, test_y = train_test_split(transformedData, digits.target, test_size=0.20, random_state=5)

lr = LogisticRegression()
lr.fit(train_x,train_y)

pred_y = lr.predict(test_x)

#Accuracy
print("Acuuracy is:: ", metrics.accuracy_score(test_y, pred_y))

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]


C:\Users\ruchika_garg01\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\ruchika_garg01\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:459: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Acuuracy is::  0.9611111111111111


# Using scikit learn perform a LDA on the dataset. Find out the number of components in the projected subspace.

In [2]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA()
lda.fit(train_x, train_y)
train_x = lda.transform(train_x)
test_x = lda.transform(test_x)

C:\Users\ruchika_garg01\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


# Transform the dataset and fit a logistic regression and observe the accuracy. Compare it with the previous model based on PCA in terms of accuracy and model complexity.

In [3]:
#train_x_pca, test_x_pca, train_y_pca, test_y_pca = train_test_split(reduced_features_df, digits.target, test_size=0.20, random_state=5)

lr1 = LogisticRegression()
lr1.fit(train_x,train_y)

pred_y = lr1.predict(test_x)

#Accuracy
print("Accuracy is:: ", metrics.accuracy_score(test_y, pred_y))

Accuracy is::  0.9388888888888889


C:\Users\ruchika_garg01\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\ruchika_garg01\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:459: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
