# BluEx is a leading logistics company in India.  It's known for efficient delivery of packets to customers.  However BluEx is facing a challenge where its vandrivers are taking a suboptimal path for delivery.  This is causing delays and higher fuel cost.You as ML expert have to create a ML model using Reinforcement Learning so that efficient path is found through the program. 

In [1]:
import numpy as np
# R matrix
R = np.matrix([ [-1,100,-1,-1,0,-1],
               [0,100,0,-1,-1,0],
               [-1,100,-1,-1,-1,-1],
               [-1,-1,-1,-1,-1,0],
               [0,-1,-1,-1,-1,0],
               [-1,100,-1,0,0,-1] ])
print(R)

[[ -1 100  -1  -1   0  -1]
 [  0 100   0  -1  -1   0]
 [ -1 100  -1  -1  -1  -1]
 [ -1  -1  -1  -1  -1   0]
 [  0  -1  -1  -1  -1   0]
 [ -1 100  -1   0   0  -1]]


In [2]:
# Q matrix
Q = np.matrix (np.zeros([6,6]))
print(Q)
# Gamma
gamma = 0.8
# Initial state
initial_state = 5

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [3]:
# This function returns all available actions in the state given as an argument
def available_actions(state):
    current_state_row = R[state,]
    av_act = np.where(current_state_row >= 0)[1]
    return av_act
# Get available actions in the current state
available_act = available_actions(initial_state)
# This function chooses at random action out of available actions
def sample_next_action(available_actions_range):
    next_action = int(np.random.choice(available_act,1))
    return next_action
# Sample next action to be performed
action = sample_next_action(available_act)

In [4]:
# This function updates the Q matrix according to the path selected and the Q learning algorithm
def update(current_state, action, gamma):  
    max_index = np.where(Q[action,] == np.max(Q[action,]))[1]
    if max_index.shape[0] > 1:
        max_index = int(np.random.choice(max_index, size = 1))
    else:
        max_index = int(max_index)
    max_value = Q[action, max_index]   
    Q[current_state, action] = R[current_state, action] + gamma * max_value
update(initial_state,action,gamma)
print(Q)

[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0. 100.   0.   0.   0.   0.]]


In [5]:
# Train over 10 000 iterations(Re-iterate the # process above)
for i in range(5000):
    current_state = np.random.randint(0, int(Q.shape[0]))
    available_act = available_actions(current_state)
    action = sample_next_action(available_act)
    update(current_state,action,gamma)
print(Q)

[[  0. 500.   0.   0. 320.   0.]
 [400. 500. 400.   0.   0. 400.]
 [  0. 500.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 400.]
 [400.   0.   0.   0.   0. 400.]
 [  0. 500.   0. 320. 320.   0.]]


In [6]:
# Normalize the "trained" Q matrix
print("Trained Q matrix:")
print(Q/np.max(Q)*100)

Trained Q matrix:
[[  0. 100.   0.   0.  64.   0.]
 [ 80. 100.  80.   0.   0.  80.]
 [  0. 100.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  80.]
 [ 80.   0.   0.   0.   0.  80.]
 [  0. 100.   0.  64.  64.   0.]]


In [8]:
current_state = 3
steps = [current_state]
while current_state != 5:
    next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[1]
    if next_step_index.shape[0] > 1:
        next_step_index = int(np.random.choice(next_step_index, size=1))
    else:
        next_step_index = int(next_step_index)
    steps.append(next_step_index)
    current_state = next_step_index
# Print selected sequence of steps
print("Selected path:")
print(steps)

Selected path:
[3, 5]
